'use strict';
// Seed content for D Cam Engineering — consolidated from dcamengineering.com + .co.in

const categories = [
  { name: 'Core Analysis Equipment', slug: 'core-analysis', sort_order: 1,
    description: 'Core holders and accumulators for petroleum, EOR and geotechnical core analysis.' },
  { name: 'High-Pressure Pumps', slug: 'high-pressure-pumps', sort_order: 2,
    description: 'Precision high-pressure syringe pumps for dosing, constant flow and constant pressure.' },
  { name: 'Flooding & Permeability Systems', slug: 'flooding-permeability', sort_order: 3,
    description: 'Core flooding apparatus and liquid/gas permeameters for reservoir studies.' },
  { name: 'Reactors & Autoclaves', slug: 'reactors-autoclaves', sort_order: 4,
    description: 'High-pressure stirred reactors and autoclaves for chemical and catalytic research.' },
];

// Shared field set is added automatically by the form renderer.
// form_fields below are the PRODUCT-SPECIFIC fields.
const products = [
  {
    category: 'core-analysis',
    name: 'Core Holder (Hassler / Hydrostatic / Triaxial)',
    slug: 'core-holder',
    short_desc: 'High-pressure core holders in Hassler, hydrostatic and triaxial configurations for oil & gas and geotechnical research.',
    long_desc: 'High-performance core holders for oil & gas research and geotechnical engineering. Available in Hassler, hydrostatic and triaxial configurations; SS or Hastelloy construction; customisable sleeves (Viton, EPDM, Teflon). Accepts cores of 1"–2" diameter and 2–18" length; rated to 10,000 psi.',
    price_mode: 'on_request', price: null, moq: '1 Piece', lead_time: '7 days – 4 weeks',
    seo_title: 'Hassler Core Holder Manufacturer & Supplier | D Cam Engineering',
    seo_meta: 'Hassler, hydrostatic and triaxial core holders rated to 10,000 psi, SS/Hastelloy, customisable sleeves. Manufactured in Ahmedabad, India. Request a quote.',
    specs: [
      { label: 'Holder Type', value: 'Hassler, Hydrostatic and Tri-Axial', meaning: 'Confining-pressure designs that simulate different underground stress conditions.' },
      { label: 'Operating Pressure', value: '10000 psi', meaning: 'Maximum safe working pressure.' },
      { label: 'Operating Temperature', value: '90 °C' },
      { label: 'Core Diameter', value: '1" & 1.5"' },
      { label: 'Core Length', value: '2–18 inches' },
      { label: 'Shank Size', value: '1", 1.5" and 2"' },
      { label: 'Material', value: 'Stainless Steel' },
      { label: 'Coating', value: 'Nickel Plated' },
      { label: 'Power Supply', value: '230V AC 50Hz' },
      { label: 'Automation Grade', value: 'Semi automatic' },
    ],
    form_fields: [
      { name: 'holder_type', label: 'Holder type', type: 'select', required: true, options: ['Hassler', 'Hydrostatic', 'Triaxial'] },
      { name: 'core_diameter', label: 'Core diameter', type: 'select', required: true, options: ['1"', '1.5"', '2"', 'Other'] },
      { name: 'core_length', label: 'Core length (inches)', type: 'text', required: false },
      { name: 'pressure_rating', label: 'Working pressure rating', type: 'select', required: true, options: ['up to 5,000 psi', 'up to 10,000 psi', 'Other'] },
      { name: 'operating_temp', label: 'Operating temperature', type: 'select', required: false, options: ['Ambient', 'up to 90 °C', 'Other'] },
      { name: 'body_material', label: 'Body material', type: 'select', required: false, options: ['Stainless Steel', 'Hastelloy', 'Other'] },
      { name: 'sleeve_material', label: 'Sleeve material', type: 'select', required: false, options: ['Viton', 'EPDM', 'Teflon'] },
    ],
  },
  {
    category: 'core-analysis',
    name: 'Floating Piston Accumulator',
    slug: 'floating-piston-accumulator',
    short_desc: 'SS316 accumulators that keep test fluids at reservoir condition, up to 1,200 bar.',
    long_desc: 'A cylinder with two end plugs and one freely-floating piston separating a driving chamber (water/silicon oil) from a test chamber (brine, oil, gas), keeping test fluids at reservoir condition. SS316; 50 ml–2 L; up to 1,200 bar; FKM (Viton) seals; threaded lock ring for safety.',
    price_mode: 'on_request', price: null, moq: '1 Piece', lead_time: '1–4 months',
    seo_title: 'Floating Piston Accumulator Manufacturer | D Cam Engineering',
    seo_meta: 'SS316 floating piston accumulators, 50 ml–2 L, up to 1,200 bar, Viton seals. Keep test fluids at reservoir condition. Made in Ahmedabad, India.',
    specs: [
      { label: 'Max Working Pressure', value: '100 to 1200 bar' },
      { label: 'Volume', value: '50 ml to 2 L' },
      { label: 'Bore Size', value: '64 mm' },
      { label: 'Shell Material', value: 'Stainless Steel SS316' },
      { label: 'Piston Seal Material', value: 'FKM (Viton)' },
      { label: 'Mounting Type', value: 'Vertical' },
      { label: 'Fluid Port Size', value: '1/2 inch' },
      { label: 'Design Code', value: 'PED' },
      { label: 'Country of Origin', value: 'India' },
    ],
    form_fields: [
      { name: 'volume', label: 'Volume / capacity', type: 'select', required: true, options: ['50 ml', '100 ml', '500 ml', '1 L', '2 L', 'Other'] },
      { name: 'max_pressure', label: 'Max working pressure', type: 'select', required: true, options: ['100 bar', '500 bar', '1000 bar', '1200 bar', 'Other'] },
      { name: 'shell_material', label: 'Shell / body material', type: 'select', required: false, options: ['SS316', 'Other'] },
      { name: 'seal_material', label: 'Piston seal material', type: 'select', required: false, options: ['FKM (Viton)', 'EPDM', 'Other'] },
      { name: 'mounting', label: 'Mounting type', type: 'select', required: false, options: ['Vertical', 'Horizontal'] },
      { name: 'port_size', label: 'Fluid port size', type: 'select', required: false, options: ['1/4"', '1/2"', 'Other'] },
      { name: 'test_fluids', label: 'Test fluids', type: 'text', required: false, placeholder: 'e.g. brine, oil, gas' },
    ],
  },
  {
    category: 'high-pressure-pumps',
    name: 'High Pressure Syringe Pump',
    slug: 'high-pressure-syringe-pump',
    short_desc: 'Digital, microprocessor-controlled syringe pump — single/dual/multi-channel, up to 20,000 psi, 0.5% accuracy.',
    long_desc: 'Digital, microprocessor-controlled electromechanical piston pump that precisely generates and regulates pressure and provides flow control. Single/dual/multi-channel; 1,500–20,000 psi; 0.0001–200 ml/min; 0.5% accuracy; RS232/USB/Ethernet. For microfluidics, chromatography, HPLC and research.',
    price_mode: 'fixed', price: 'From Rs 17,85,000 (final price on request)', moq: '1 Piece', lead_time: '1–4 months',
    seo_title: 'High Pressure Syringe Pump Manufacturer | D Cam Engineering',
    seo_meta: 'High pressure syringe pump up to 20,000 psi, 0.5% accuracy, single/dual/multi-channel, RS232/USB/Ethernet. For HPLC, microfluidics and research. India.',
    specs: [
      { label: 'Max Pressure', value: '1500 - 20000 psi' },
      { label: 'Number of Channels', value: 'Single, Dual and Multi channel' },
      { label: 'Syringe Size', value: '25 ml to 1000 ml' },
      { label: 'Flow Rate Range', value: '0.0001 to 200 ml/min' },
      { label: 'Accuracy', value: '0.5 %' },
      { label: 'Control Mode', value: 'Volume, Pressure and Flow Rate Control' },
      { label: 'Communication Interface', value: 'RS232, USB, Ethernet' },
      { label: 'Application', value: 'Microfluidics, Chromatography, HPLC, Research Lab' },
      { label: 'Power Supply', value: '220-240 V AC' },
      { label: 'Warranty', value: '1 year' },
    ],
    form_fields: [
      { name: 'channels', label: 'Number of channels', type: 'select', required: true, options: ['Single', 'Dual', 'Multi'] },
      { name: 'max_pressure', label: 'Max pressure', type: 'select', required: true, options: ['1,500 psi', '5,000 psi', '10,000 psi', '20,000 psi', 'Other'] },
      { name: 'syringe_size', label: 'Syringe / cylinder size', type: 'select', required: true, options: ['25 ml', '100 ml', '250 ml', '500 ml', '1000 ml', 'Other'] },
      { name: 'flow_rate', label: 'Flow-rate range', type: 'text', required: false, placeholder: 'e.g. 0.001–50 ml/min' },
      { name: 'control_mode', label: 'Control mode', type: 'text', required: false, placeholder: 'Volume / Pressure / Flow rate' },
      { name: 'interface', label: 'Communication interface', type: 'text', required: false, placeholder: 'RS232 / USB / Ethernet' },
      { name: 'application', label: 'Application', type: 'select', required: false, options: ['Microfluidics', 'Chromatography', 'HPLC', 'Industrial', 'Research'] },
    ],
  },
  {
    category: 'flooding-permeability',
    name: 'Core Flooding Apparatus',
    slug: 'core-flooding-apparatus',
    short_desc: 'EOR research apparatus — injects fluids into rock cores to measure permeability and fluid–rock interactions. Up to 700 bar, 150 °C.',
    long_desc: 'Injects fluid(s) into a rock sample to determine permeability, relative permeability, saturation change, formation damage and fluid–rock interactions. Built to evaluate Enhanced Oil Recovery (EOR) strategies. SS frame; 230 V; up to 700 bar & 150 °C; PC data interface; manual to semi-automatic.',
    price_mode: 'on_request', price: null, moq: '1 Piece', lead_time: '4 months',
    seo_title: 'Core Flooding Apparatus Manufacturer | D Cam Engineering',
    seo_meta: 'Core flooding apparatus for EOR research — up to 700 bar & 150 °C, PC data interface, manual to semi-automatic. Manufactured in Ahmedabad, India.',
    specs: [
      { label: 'Equipment Type', value: 'EOR Research Apparatus' },
      { label: 'Required Pressure', value: '700 Bar' },
      { label: 'Working Temperature', value: '150 °C' },
      { label: 'Operation Mode', value: 'Manual and semi Automatic' },
      { label: 'Frame Material', value: 'Stainless Steel' },
      { label: 'Data Output', value: 'PC Interface' },
      { label: 'Mobility', value: 'Floor Mounted' },
      { label: 'Power Requirement', value: '230 V AC' },
      { label: 'Application', value: 'Teaching Lab, Research Lab, Industrial Test' },
    ],
    form_fields: [
      { name: 'automation', label: 'Automation grade', type: 'select', required: true, options: ['Manual', 'Semi-automatic', 'Fully automatic'] },
      { name: 'core_lines', label: 'Number of core holders / lines', type: 'select', required: false, options: ['1', '2', '3', 'Other'] },
      { name: 'max_pressure', label: 'Max pressure', type: 'select', required: true, options: ['up to 700 bar', 'Other'] },
      { name: 'working_temp', label: 'Working temperature', type: 'select', required: false, options: ['Ambient', 'up to 150 °C', 'Other'] },
      { name: 'pumps', label: 'Number of pumps / accumulators', type: 'text', required: false },
      { name: 'application', label: 'Application', type: 'select', required: false, options: ['Teaching lab', 'Research lab', 'Industrial test'] },
      { name: 'pc_interface', label: 'PC / data interface required?', type: 'select', required: false, options: ['Yes', 'No'] },
    ],
  },
  {
    category: 'flooding-permeability',
    name: 'Liquid Permeameter',
    slug: 'liquid-permeameter',
    short_desc: 'Digital instrument to measure liquid permeability of soil/core samples. Falling-head, automatic, SS construction.',
    long_desc: 'Digital, microprocessor-controlled instrument to measure the permeability of soil/core samples to liquids for laboratory and industrial testing. Falling-head type; 50 mm sample; automatic; SS construction.',
    price_mode: 'on_request', price: null, moq: '10 Piece', lead_time: '10 days',
    seo_title: 'Liquid Permeameter Manufacturer | D Cam Engineering',
    seo_meta: 'Digital liquid permeameter for soil/core permeability testing — falling head, automatic, stainless steel. Manufactured in Ahmedabad, India.',
    specs: [
      { label: 'Type', value: 'Falling Head' },
      { label: 'Fluid Type', value: 'Liquid' },
      { label: 'Automation Grade', value: 'Automatic' },
      { label: 'Display Type', value: 'Digital' },
      { label: 'Diameter', value: '50 mm' },
      { label: 'Accuracy', value: '2 %' },
      { label: 'Material', value: 'Stainless Steel' },
      { label: 'Application Type', value: 'Laboratory' },
    ],
    form_fields: [
      { name: 'method', label: 'Method / principle', type: 'select', required: false, options: ['Falling head', 'Constant head', 'Steady-state'] },
      { name: 'sample_diameter', label: 'Sample diameter', type: 'select', required: true, options: ['50 mm', '1"', '1.5"', 'Other'] },
      { name: 'sample_length', label: 'Sample length', type: 'text', required: false },
      { name: 'automation', label: 'Automation grade', type: 'select', required: false, options: ['Manual', 'Automatic', 'Digital display'] },
    ],
  },
  {
    category: 'flooding-permeability',
    name: 'Gas Permeameter',
    slug: 'gas-permeameter',
    short_desc: 'Instrument for measuring gas permeability of core/soil samples. SS, 220 V, lab/industrial use.',
    long_desc: 'Instrument for measuring gas permeability of core/soil samples. Stainless steel construction; electric 220 V; laboratory/industrial use; 1-year warranty.',
    price_mode: 'on_request', price: null, moq: '10 Piece', lead_time: '10 days',
    seo_title: 'Gas Permeameter Manufacturer | D Cam Engineering',
    seo_meta: 'Gas permeameter for measuring gas permeability of core/soil samples — stainless steel, 220 V, lab/industrial. Manufactured in Ahmedabad, India.',
    specs: [
      { label: 'Type', value: 'Gas Permeameter' },
      { label: 'Material', value: 'Stainless Steel' },
      { label: 'Power Supply', value: 'Electric, 220 Volt' },
      { label: 'Size', value: 'Standard' },
      { label: 'Usage', value: 'Industrial / Laboratory' },
      { label: 'Warranty', value: '1 Year' },
    ],
    form_fields: [
      { name: 'method', label: 'Method / principle', type: 'select', required: false, options: ['Steady-state', 'Unsteady-state', 'Other'] },
      { name: 'sample_diameter', label: 'Sample diameter', type: 'select', required: true, options: ['50 mm', '1"', '1.5"', 'Other'] },
      { name: 'gas_type', label: 'Gas type', type: 'text', required: false, placeholder: 'e.g. Nitrogen, Air' },
      { name: 'automation', label: 'Automation grade', type: 'select', required: false, options: ['Manual', 'Automatic', 'Digital display'] },
    ],
  },
  {
    category: 'reactors-autoclaves',
    name: 'High Pressure Stirrer Reactor',
    slug: 'high-pressure-stirrer-reactor',
    short_desc: 'Jacketed stirred-tank reactor (SS-316L) for polymerisation, hydrogenation and catalytic tests. Up to 500 bar, 500 °C.',
    long_desc: 'High-pressure jacketed stirred-tank reactor (SS-316L) for polymerisation, hydrogenation, supercritical and catalytic tests. 50 ml–5 L; up to 500 bar & 500 °C; magnetic or overhead stirring; safety valve, rupture disc, pressure switch & data logger; manual to fully automatic.',
    price_mode: 'on_request', price: null, moq: '1 Unit', lead_time: '8–12 weeks',
    seo_title: 'High Pressure Stirrer Reactor / Autoclave Manufacturer | D Cam Engineering',
    seo_meta: 'High pressure stirred reactor (autoclave), 50 ml–5 L, up to 500 bar & 500 °C, SS316/Hastelloy/Inconel/Titanium. Made in Ahmedabad, India.',
    specs: [
      { label: 'Reactor Capacity', value: '50 ml to 5 liter' },
      { label: 'Design Pressure', value: '500 bar' },
      { label: 'Design Temperature', value: '500 °C' },
      { label: 'Material of Construction', value: 'SS316, Hastelloy, Inconel, Titanium, Alloy Steel' },
      { label: 'Stirring Option', value: 'Magnetic and Overhead' },
      { label: 'Automation Grade', value: 'Manual, Semi Auto and Fully Auto' },
      { label: 'Safety Features', value: 'Rupture Disc, Safety Valve, Pressure Switch, Data Logger' },
      { label: 'Closure Type', value: 'Split Ring' },
      { label: 'Application', value: 'Polymerization, Supercritical, Hydrogenation, Catalytic Tests' },
    ],
    form_fields: [
      { name: 'capacity', label: 'Reactor capacity', type: 'select', required: true, options: ['50 ml', '250 ml', '500 ml', '1 L', '2 L', '5 L', 'Other'] },
      { name: 'design_pressure', label: 'Design pressure', type: 'select', required: true, options: ['up to 200 bar', 'up to 400 bar', 'up to 500 bar', 'Other'] },
      { name: 'design_temp', label: 'Design temperature', type: 'select', required: false, options: ['up to 300 °C', 'up to 500 °C', 'Other'] },
      { name: 'material', label: 'Material of construction', type: 'select', required: true, options: ['SS316', 'Hastelloy', 'Inconel', 'Titanium', 'Alloy steel'] },
      { name: 'stirring', label: 'Stirring option', type: 'select', required: false, options: ['Magnetic', 'Overhead'] },
      { name: 'automation', label: 'Automation grade', type: 'select', required: false, options: ['Manual', 'Semi-auto', 'Fully auto'] },
      { name: 'application', label: 'Application', type: 'select', required: false, options: ['Polymerisation', 'Hydrogenation', 'Supercritical', 'Catalytic', 'Batch'] },
    ],
  },
];

const testimonials = [
  { reviewer: 'Clive', location: 'Portugal', rating: 5, date: '10 May 2023', product: 'High Pressure Syringe Pump', body: 'Excellent equipment and support.', sort_order: 1 },
  { reviewer: 'Qasem Saloom', location: 'Iraq', rating: 5, date: '19 Jun 2021', product: '', body: '', sort_order: 2 },
  { reviewer: 'Qasem A. Saloom', location: 'Iraq', rating: 4, date: '23 Jun 2021', product: '', body: '', sort_order: 3 },
  { reviewer: 'Shilpa Nandwani', location: 'Surat, India', rating: 4, date: '13 May 2021', product: '', body: '', sort_order: 4 },
  { reviewer: 'Dody', location: 'Indonesia', rating: 3, date: '06 Sep 2019', product: 'High Pressure Syringe Pump', body: '', sort_order: 5 },
];

module.exports = { categories, products, testimonials };
